/**
 * Challan Generator Page
 * 
 * Generate Challan 280 summary for income tax payments.
 * Auto-calculates surcharge and cess.
 * Provides PDF download and link to NSDL payment portal.
 */

import { useState } from 'react';
import API from '../config/api';
import { formatCurrency } from '../utils/taxCalculations';
import { jsPDF } from 'jspdf';
import toast from 'react-hot-toast';
import {
  HiOutlineCurrencyRupee,
  HiOutlineDownload,
  HiOutlineExternalLink,
  HiOutlineDocumentText,
} from 'react-icons/hi';

const ChallanPage = () => {
  // Form state
  const [formData, setFormData] = useState({
    assessmentYear: '2026-27',
    taxAmount: '',
    surcharge: '',
    paymentType: 'Advance Tax',
  });

  const [challan, setChallan] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  // Assessment year options
  const assessmentYears = ['2026-27', '2025-26', '2024-25'];

  // Payment type options
  const paymentTypes = [
    'Advance Tax',
    'Self-Assessment Tax',
    'Regular Assessment Tax',
  ];

  /**
   * Generate a challan by saving to DB and calculating cess
   */
  const handleGenerate = async (e) => {
    e.preventDefault();

    if (!formData.taxAmount || Number(formData.taxAmount) <= 0) {
      toast.error('Please enter a valid tax amount');
      return;
    }

    setIsLoading(true);

    try {
      const response = await API.post('/challan/generate', {
        assessmentYear: formData.assessmentYear,
        taxAmount: Number(formData.taxAmount),
        surcharge: Number(formData.surcharge) || 0,
        paymentType: formData.paymentType,
      });

      setChallan(response.data);
      toast.success('Challan generated!');
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to generate challan');
    } finally {
      setIsLoading(false);
    }
  };

  /**
   * Download the challan as a PDF
   */
  const downloadPDF = () => {
    if (!challan) return;

    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(26, 86, 219);
    doc.text('CHALLAN NO. ITNS 280', 105, 25, { align: 'center' });

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('(Income Tax on Companies / Other Than Companies)', 105, 33, { align: 'center' });

    // Line
    doc.setDrawColor(26, 86, 219);
    doc.setLineWidth(0.5);
    doc.line(20, 38, 190, 38);

    // Challan Details
    doc.setFontSize(11);
    doc.setTextColor(0);
    let y = 52;
    const leftX = 25;
    const rightX = 120;

    const addRow = (label, value) => {
      doc.setTextColor(80);
      doc.text(label, leftX, y);
      doc.setTextColor(0);
      doc.setFont(undefined, 'bold');
      doc.text(value, rightX, y);
      doc.setFont(undefined, 'normal');
      y += 10;
    };

    addRow('Assessment Year:', challan.assessmentYear);
    addRow('Payment Type:', challan.paymentType);

    y += 5;
    doc.setDrawColor(200);
    doc.line(20, y, 190, y);
    y += 10;

    addRow('Tax Amount:', formatCurrency(challan.taxAmount));
    addRow('Surcharge:', formatCurrency(challan.surcharge));
    addRow('Health & Education Cess (4%):', formatCurrency(challan.cess));

    y += 5;
    doc.setDrawColor(200);
    doc.line(20, y, 190, y);
    y += 10;

    doc.setFontSize(14);
    doc.setTextColor(26, 86, 219);
    doc.setFont(undefined, 'bold');
    doc.text('Total Amount Payable:', leftX, y);
    doc.text(formatCurrency(challan.totalAmount), rightX, y);
    doc.setFont(undefined, 'normal');

    // Payment Instructions
    y += 25;
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text('HOW TO PAY:', leftX, y);
    y += 8;
    doc.setFontSize(9);
    doc.text('1. Visit https://onlineservices.tin.egov-nsdl.com/etaxnew/tdsnontds.jsp', leftX, y); y += 6;
    doc.text('2. Select "CHALLAN NO./ITNS 280"', leftX, y); y += 6;
    doc.text('3. Select "Tax Applicable: (0021) Income Tax (Other than Companies)"', leftX, y); y += 6;
    doc.text('4. Fill in PAN, Assessment Year, and other details', leftX, y); y += 6;
    doc.text('5. Choose net banking or debit card to make payment', leftX, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by SmartTax — Educational Project', 105, 280, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });

    doc.save(`Challan_280_AY${challan.assessmentYear}.pdf`);
    toast.success('Challan PDF downloaded!');
  };

  return (
    <div className="page-container animate-fadeIn">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="section-heading mb-0">Challan 280 Generator</h1>
          <p className="text-gray-600">Generate tax payment challan with auto-calculated cess</p>
        </div>

        {/* Form */}
        <div className="card mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center">
            <HiOutlineCurrencyRupee className="w-6 h-6 mr-2 text-primary-500" />
            Payment Details
          </h2>
          <form onSubmit={handleGenerate} className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="input-label">Assessment Year</label>
              <select
                value={formData.assessmentYear}
                onChange={(e) => setFormData({ ...formData, assessmentYear: e.target.value })}
                className="input-field"
              >
                {assessmentYears.map((ay) => (
                  <option key={ay} value={ay}>AY {ay}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="input-label">Payment Type</label>
              <select
                value={formData.paymentType}
                onChange={(e) => setFormData({ ...formData, paymentType: e.target.value })}
                className="input-field"
              >
                {paymentTypes.map((type) => (
                  <option key={type} value={type}>{type}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="input-label">Tax Amount (₹)</label>
              <input
                type="number"
                value={formData.taxAmount}
                onChange={(e) => setFormData({ ...formData, taxAmount: e.target.value })}
                placeholder="e.g., 50000"
                className="input-field"
                required
              />
            </div>
            <div>
              <label className="input-label">Surcharge (₹) — if applicable</label>
              <input
                type="number"
                value={formData.surcharge}
                onChange={(e) => setFormData({ ...formData, surcharge: e.target.value })}
                placeholder="0"
                className="input-field"
              />
            </div>

            {/* Preview calculation */}
            {formData.taxAmount && (
              <div className="md:col-span-2 p-4 bg-blue-50 rounded-lg border border-blue-200">
                <p className="text-sm text-blue-800">
                  <strong>Preview:</strong> Tax {formatCurrency(Number(formData.taxAmount))} + 
                  Surcharge {formatCurrency(Number(formData.surcharge) || 0)} + 
                  Cess {formatCurrency(Math.round((Number(formData.taxAmount) + (Number(formData.surcharge) || 0)) * 0.04))} = 
                  <strong> {formatCurrency(Number(formData.taxAmount) + (Number(formData.surcharge) || 0) + Math.round((Number(formData.taxAmount) + (Number(formData.surcharge) || 0)) * 0.04))}</strong>
                </p>
              </div>
            )}

            <div className="md:col-span-2">
              <button type="submit" disabled={isLoading} className="btn-primary w-full sm:w-auto">
                {isLoading ? 'Generating...' : 'Generate Challan'}
              </button>
            </div>
          </form>
        </div>

        {/* Generated Challan */}
        {challan && (
          <div className="card animate-slideUp">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900 flex items-center">
                <HiOutlineDocumentText className="w-6 h-6 mr-2 text-primary-500" />
                Challan 280 — Generated
              </h3>
              <span className="badge bg-green-100 text-green-700">✓ Ready</span>
            </div>

            <div className="space-y-3 text-sm">
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-600">Assessment Year</span>
                <span className="font-medium">AY {challan.assessmentYear}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-600">Payment Type</span>
                <span className="font-medium">{challan.paymentType}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-600">Tax Amount</span>
                <span className="font-medium">{formatCurrency(challan.taxAmount)}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-600">Surcharge</span>
                <span className="font-medium">{formatCurrency(challan.surcharge)}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-600">Health & Education Cess (4%)</span>
                <span className="font-medium">{formatCurrency(challan.cess)}</span>
              </div>
              <div className="flex justify-between py-3 text-lg">
                <span className="font-semibold text-gray-900">Total Amount</span>
                <span className="font-bold text-primary-600">{formatCurrency(challan.totalAmount)}</span>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-3 mt-6">
              <button onClick={downloadPDF} className="btn-primary flex items-center justify-center flex-1">
                <HiOutlineDownload className="w-5 h-5 mr-2" />
                Download Challan PDF
              </button>
              <a
                href="https://onlineservices.tin.egov-nsdl.com/etaxnew/tdsnontds.jsp"
                target="_blank"
                rel="noopener noreferrer"
                className="btn-secondary flex items-center justify-center flex-1"
              >
                <HiOutlineExternalLink className="w-5 h-5 mr-2" />
                Pay on NSDL Portal
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ChallanPage;
